/* This program is to filter the SITS export file, throwing away
   all <group> and <membership> records that don't correspond to
   courses already in WebCT. */

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>

typedef struct modulelist {
        char *name;
        struct modulelist *next;
} modulelist;

typedef struct linelist {
        char *data;
        struct linelist *next;
} linelist;

typedef struct savelist {
        char name[10];
        struct linelist *first;
        struct savelist *next;
} savelist;

main () {
   FILE *f;
   modulelist *modules, *m;
   linelist *lines, *l, **lastline;
   savelist *saved = NULL, *sav2;
   char line[200], line2[200];
   char thismodule[] = ",XXXXXXXXX,";
   char *s, *s2, *mem, tag[15];
   int length, copy, saving=0;
   char *p;
   char accented[] = "\
\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\
\xd1\xd2\xd3\xd4\xd5\xd6\xd8\xd9\xda\xdb\xdc\xdd\xdf\
\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\
\xf1\xf2\xf3\xf4\xf5\xf6\xf8\xf9\xfa\xfb\xfc\xfd\xff";
   char replacement[] = "\
AAAAAAECEEEEIIII\
NOOOOOOUUUUYs\
aaaaaaeceeeeiiii\
noooooouuuuyy";

/* We first read in all the WebCT course names that appear to be
   module names - this is read from file "modules_webct" and stored
   in a linked list.  This file was generated by hand using the
   WebCT admin interface.  I don't know of a scriptable way to do it. */

   modules = NULL;
   f = fopen ("/data/moodle/1/module_list.txt", "r");
/* f = fopen ("WebCT_module_list.txt", "r"); */
   while (fgets (line, 200, f)) {
/*      length = strlen (line);
      if (line[length-2] == '\r') {
         line[length-2] = '\n';
         line[length-1] = '\0';
      } */
      while (strchr ("\n\r", line[strlen(line)-1]))
         line[strlen(line)-1] = '\0';
      m = (modulelist *) malloc (sizeof (modulelist));
      m->name = (char *) malloc (strlen(line)+1);
      strcpy (m->name, line);
      m->name[strlen(line)] = ',';
      if (s = strchr (m->name, ':')) {
         *s = ',';
      }
      m->next = modules;
      modules = m;
   }
   fclose (f); 

/* We now open the SITS import file "/nfs/rcs/sysman/cso/sits/webct_SIS.xml",
   and copy it, searching for lines containing "<group>" or "<membership>" */

   f = fopen ("/nfs/rcs/sysman/cso/sits/webct_SIS.xml", "r");
   while (fgets (line, 200, f)) {
      if ((s = mem = strstr (line, "<membership>")) ||
            (s = strstr (line, "<group>"))) {

/* We've found one of those tags, so we
   save away the corresponding closing tag */

         strcpy (tag+1, s);
         tag[0] = '<';
         tag[1] = '/';

         lines = NULL;
         lastline = &lines;

/* Now find the line containing the "<id>" tag, which contains
   the module name.  Save any intermediate lines away in a linked
   list in case we need to print them later. */

         do {
            l = (linelist *) malloc (sizeof (linelist));
            l->data = (char *) malloc (1 + strlen (line));
            strcpy (l->data, line);
            l->next = NULL;
            *lastline = l;
            lastline = &(l->next);
            fgets (line, 200, f);
         } while ((s = strstr (line, "<id>")) == NULL);

/* See if any of the list of WebCT course names forms the first
   eight characters of the SITS module name.  If there's a match,
   we want to copy this whole section, otherwise we want to skip it. */

         copy = 0;
length = strchr(s+4,'/')-s-9;
         strncpy (thismodule+1, s+4, length);
thismodule[length+1] = ',';
thismodule[length+2] = '\0';
         for (m = modules; m != NULL; m = m->next) {
            if (mem && strstr (m->name, thismodule)) {
               sav2 = (savelist *) malloc (sizeof (savelist));
               strcpy (sav2->name, thismodule+1);
               sav2->name[length] = '\0';
               sav2->first = NULL;
               lastline = &(sav2->first);
               sav2->next = saved;
               saved = sav2;
               saving = 1;
            }
            if (strcmp (thismodule+1, m->name) == 0) {

/* There's a match - put out the lines we've been holding back */

               copy = 1;
               for (l = lines; l != NULL; l = l->next)
                  printf ("%s", l->data);

/* truncate the module name in the <id> field to eight characters */

               s2 = s+4;
               s2 = strstr (s2, "<");
               *(s+12) = '\0';
               printf ("%s%s", line, s2);
            }
         }

/* de-allocate the memory grabbed for the linked list of lines */

         while (lines) {
            l = lines->next;
            free (lines->data);
            free (lines);
            lines = l;
         }

/* Copy (or skip) up to the closing tag of this section */

         do {
            fgets (line, 200, f);
            if (copy)
               printf ("%s", line);
            if (saving) {
               l = (linelist *) malloc (sizeof (linelist));
               l->data = (char *) malloc (1 + strlen (line));
               strcpy (l->data, line);
               l->next = NULL;
               *lastline = l;
               lastline = &(l->next);
            }
         } while (strstr (line, tag) == 0);
         saving = 0;
      }
      else {
         if (strstr (line, "</enterprise>")) {
            for (m = modules; m != NULL; m = m->next)
            if (strlen (m->name) > 9)  {
               strcpy (line2, m->name);
               s = strchr (line2, ',');
               *s = '\0';
               s++;
               printf ("<membership>\n");
               printf ("  <sourcedid>\n");
               printf ("    <source>sits:vision</source>\n");
               printf ("    <id>%s</id>\n", line2);
               printf ("  </sourcedid>\n");

               while (s2 = strchr (s, ',')) {
                  *s2 = '\0';
                  for (sav2 = saved; sav2 != NULL; sav2 = sav2->next)
                  if (strcmp (s, sav2->name) == 0) {
                     for (l = sav2->first->next; l->next != NULL; l = l->next)
                        printf ("%s", l->data);
break;
                  }
                  s = s2+1;
               }
               printf ("</membership>\n");
            }
         }
         while (p = strpbrk (line, accented)) {
            *p = replacement[strchr (accented, *p) - accented];
         }
         printf ("%s", line);
      }
   }
}
